// this is your main.js script
// Exercise 1
let challenge = '30 Days of Javascript'
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substring(3))
console.log(challenge.substring(0, 3))
console.log(challenge.includes('Script'))
console.log(challenge.split())
console.log(challenge.split(' '))
console.log('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(', '))
console.log(challenge.replace('Javascript', 'Python'))
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt(11))
console.log(challenge.indexOf('a'))
console.log('You cannot end a sentence with because because because is a conjunction'.indexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction'.lastIndexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction'.search('because'))
console.log(' 30 Days Of JavaScript '.trim())
console.log(challenge.startsWith('30'))
console.log(challenge.endsWith('script'))
console.log(challenge.match(/a/g))
console.log('30 Dyas of'.concat(' Javascript'))
console.log(challenge.repeat(2))